remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Reasonably Integrated
description: Shower thoughts and views on the journey into madness/Azure Integrations
